
package br.com.mensagem.servicoMensagemWS;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ManterPessoaFault", targetNamespace = "http://servicomensagens.faeterj.com.br/manterpessoaws")
public class ManterPessoaFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ManterPessoaFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ManterPessoaFaultException(String message, ManterPessoaFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ManterPessoaFaultException(String message, ManterPessoaFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.faeterj.servicomensagens.manterpessoaws.ManterPessoaFault
     */
    public ManterPessoaFault getFaultInfo() {
        return faultInfo;
    }

}
